created helmcharts for adcorner service
cheddartv/helm-charts pull request #42
Opened 2023-02-01 22:15 UTC by priya64646

created helmcharts for adcorner service

2023-02-16 17:01 UTC, pankajnarang commented on charts/AdCorner/README.md
> +#Plan - Helm chart
Shouldn't this be Adcorner?

2023-02-16 17:02 UTC, pankajnarang requested changes
Readme needs to be updated

2023-02-17 17:47 UTC, priya64646 commented on charts/AdCorner/README.md
> +#Plan - Helm chart
Done @pankajnarang

2023-02-17 19:16 UTC, pankajnarang approved these changes

2023-02-22 16:43 UTC, merged